/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyInvitationsRouteImport } from './routes/my-invitations'
import { Route as CreateTemplateIdRouteImport } from './routes/create.$templateId'
import { Route as InviteSlugRouteImport } from './routes/invite.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyInvitationsRoute = MyInvitationsRouteImport.update({
  id: '/my-invitations',
  path: '/my-invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTemplateIdRoute = CreateTemplateIdRouteImport.update({
  id: '/create/$templateId',
  path: '/create/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteSlugRoute = InviteSlugRouteImport.update({
  id: '/invite/$slug',
  path: '/invite/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-invitations': typeof MyInvitationsRoute
  '/create/$templateId': typeof CreateTemplateIdRoute
  '/invite/$slug': typeof InviteSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-invitations': typeof MyInvitationsRoute
  '/create/$templateId': typeof CreateTemplateIdRoute
  '/invite/$slug': typeof InviteSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-invitations': typeof MyInvitationsRoute
  '/create/$templateId': typeof CreateTemplateIdRoute
  '/invite/$slug': typeof InviteSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/my-invitations' | '/create/$templateId' | '/invite/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/my-invitations' | '/create/$templateId' | '/invite/$slug'
  id:
    | '__root__'
    | '/'
    | '/my-invitations'
    | '/create/$templateId'
    | '/invite/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyInvitationsRoute: typeof MyInvitationsRoute
  CreateTemplateIdRoute: typeof CreateTemplateIdRoute
  InviteSlugRoute: typeof InviteSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-invitations': {
      id: '/my-invitations'
      path: '/my-invitations'
      fullPath: '/my-invitations'
      preLoaderRoute: typeof MyInvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/$templateId': {
      id: '/create/$templateId'
      path: '/create/$templateId'
      fullPath: '/create/$templateId'
      preLoaderRoute: typeof CreateTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$slug': {
      id: '/invite/$slug'
      path: '/invite/$slug'
      fullPath: '/invite/$slug'
      preLoaderRoute: typeof InviteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyInvitationsRoute: MyInvitationsRoute,
  CreateTemplateIdRoute: CreateTemplateIdRoute,
  InviteSlugRoute: InviteSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
